name: ArtForest
version: ${project.version}
main: net.kunmc.lab.artforest.ArtForest
api-version: 1.15
loadbefore: [ ArtMap ]
authors: [ Kei ]
depend:
  - Netherboard
description: Oekakino mori for minecraft
commands:
  af:
    usage: /af
