name: ArtForest
version: ${project.version}
main: net.kunmc.lab.artforest.ArtForest
api-version: 1.16
loadbefore: [ ArtMap ]
authors: [ Kei ]
description: Oekakino mori for minecraft
commands:
  af:
    usage: /af
